# Generated by Django 2.2.4 on 2019-09-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('room', models.PositiveSmallIntegerField()),
                ('parents_name', models.CharField(max_length=100)),
                ('parents_contact', models.IntegerField()),
                ('parents_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
