# Generated by Django 2.2.4 on 2019-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_contact',
            field=models.BigIntegerField(),
        ),
    ]
