# Generated by Django 2.2.4 on 2019-09-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewEntry', '0002_auto_20190901_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
