# Generated by Django 2.2.4 on 2019-10-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewEntry', '0003_student_stud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
