# Generated by Django 2.2.4 on 2019-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewEntry', '0005_auto_20191007_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
