# Generated by Django 2.2.4 on 2019-09-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField()),
                ('IN', models.DateTimeField()),
                ('OUT', models.DateTimeField()),
            ],
        ),
    ]
