# Generated by Django 2.2.4 on 2019-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterleave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='IN',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inout',
            name='OUT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
